// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogPhSqP8rg2la0YUJi-qxGPquex176Ww',
    appId: '1:1072437987168:web:278aaaaa32002e07a6c005',
    messagingSenderId: '1072437987168',
    projectId: 'shop-be2cb',
    authDomain: 'shop-be2cb.firebaseapp.com',
    storageBucket: 'shop-be2cb.firebasestorage.app',
    measurementId: 'G-0P8HGPC07J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAoulCaMCIok1t56RLnepkjYtlHOeYuI',
    appId: '1:1072437987168:android:ed975170a08793e7a6c005',
    messagingSenderId: '1072437987168',
    projectId: 'shop-be2cb',
    storageBucket: 'shop-be2cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTN-qAOwPU59Cp9GyqsGqjJJFKcIUBHc',
    appId: '1:1072437987168:ios:6e16589d340183f4a6c005',
    messagingSenderId: '1072437987168',
    projectId: 'shop-be2cb',
    storageBucket: 'shop-be2cb.firebasestorage.app',
    iosBundleId: 'com.once.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTN-qAOwPU59Cp9GyqsGqjJJFKcIUBHc',
    appId: '1:1072437987168:ios:6e16589d340183f4a6c005',
    messagingSenderId: '1072437987168',
    projectId: 'shop-be2cb',
    storageBucket: 'shop-be2cb.firebasestorage.app',
    iosBundleId: 'com.once.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAogPhSqP8rg2la0YUJi-qxGPquex176Ww',
    appId: '1:1072437987168:web:523d9ee58adaff0ea6c005',
    messagingSenderId: '1072437987168',
    projectId: 'shop-be2cb',
    authDomain: 'shop-be2cb.firebaseapp.com',
    storageBucket: 'shop-be2cb.firebasestorage.app',
    measurementId: 'G-NNXL8QLPW1',
  );
}
